version: '2'
services:
 jupyter:
  image: tf_pycar
  environment:
    - PYTHONPATH = /notebooks/src
  container_name: jupyter_car
  build: .
  volumes:
   - ./files:/notebooks
  ports:
   - "8880:8880"
   - "6006:6006"
   - "8886:8886"